version: '3.8'

services:
    postgres_local:
        image: postgres:15-alpine
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5434:5432
        volumes:
            - pg_data_local:/var/lib/postgresql/data
        networks:
            - softpay_pos_network_local

    redis:
        image: redis:7.2
        command: redis-server
        env_file:
            - .env
        ports:
            - '6377:6379'
        volumes:
            - redis_data_local:/data
        networks:
            - softpay_pos_network_local

volumes:
    pg_data_local:
    redis_data_local:

networks:
    softpay_pos_network_local:
        driver: bridge